In [3]:
a=[1,23,43,]
print(a)

[1, 23, 43]


In [7]:
b=[12,23,45]
print(b)


[12, 23, 45]


In [9]:
type(b)

list

In [ ]:
PYTHON

In [1]:
set_var=set()
print(set_var)
type(set_var)

set()


set

In [3]:
set1={"xyz","yazz","axzbx"}
print(set1)

{'yazz', 'axzbx', 'xyz'}


In [5]:
set1.add("hkahgsb")
print(set1)

{'hkahgsb', 'yazz', 'axzbx', 'xyz'}


In [7]:
set2={"hkahgsb","yazz","axzbx","xyx","xyz"}
print(set2)

{'hkahgsb', 'yazz', 'axzbx', 'xyz', 'xyx'}


In [11]:
set2.difference(set1)

{'xyx'}

In [31]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [33]:
for i in thisdict:
    print(i)

brand
model
year


In [41]:
for x in thisdict.values():
    print(x)

Ford
Mustang
1964


In [43]:
thisdict['color']='gold'
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'color': 'gold'}


In [45]:
thisdict['brand']='BMW'
print(thisdict)

{'brand': 'BMW', 'model': 'Mustang', 'year': 1964, 'color': 'gold'}


In [5]:
my_tuple=("anurag","anurag","divyanshu","ayush")
print(my_tuple)

('anurag', 'anurag', 'divyanshu', 'ayush')


In [7]:
my_tuple.count('anurag')
my_tuple.index('ayush')

3

In [9]:
my_tuple.count('anurag')


2

In [11]:
import numpy as np

In [13]:
my_lst=[1,2,3,4,5]
arr=np.array(my_lst)

In [15]:
type(arr)

numpy.ndarray

In [17]:
print(arr)

[1 2 3 4 5]


In [19]:
arr.shape

(5,)

In [21]:
arr[3]

4

In [23]:
arr1=np.array([[1,2,3,4,5],[2,3,4,5,6],[9,7,6,8,9]])
print(arr1)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [27]:
arr1[1:,3:]

array([[5, 6],
       [8, 9]])

In [35]:
arr2=np.arange(0,10,2)
print(arr2)

[0 2 4 6 8]


In [37]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [39]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [43]:
np.random.rand(3,3)

array([[0.33945933, 0.51368065, 0.93475826],
       [0.68850966, 0.19184939, 0.65686657],
       [0.09509361, 0.02557511, 0.46173353]])

In [45]:
np.random.rand(3)

array([0.25000413, 0.72185033, 0.37850299])

In [49]:
np.random.randint(1,100,8)

array([98, 37, 60, 24, 75, 39, 24, 55])

In [51]:
np.random.random_sample((1,5))

array([[0.51173343, 0.37992491, 0.37682206, 0.87787223, 0.19226177]])

In [53]:
import pandas as pd

In [65]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4),index=['r1','r2','r3','r4','r5'],columns=['c1','c2','c3','c4'])

In [67]:
df.head()

c1  c2  c3  c4
r1   0   1   2   3
r2   4   5   6   7
r3   8   9  10  11
r4  12  13  14  15
r5  16  17  18  19

In [69]:
df.loc['r1']

c1    0
c2    1
c3    2
c4    3
Name: r1, dtype: int32

In [71]:
df.iloc[0:2,0:3]

c1  c2  c3
r1   0   1   2
r2   4   5   6

In [75]:
jabber=open('pythonfilehandaling.txt','r')
for line in jabber:
    print(line)
jabber.close()

python file handling

Based on the provided search results, here’s a comprehensive answer on Python file handling:



To work with files in Python, you’ll primarily use the open() function, which provides various access modes for reading and writing files. Here’s a breakdown of the essential concepts and code examples:



File Access Modes:

r - Read mode (default): Opens the file for reading. The file pointer is placed at the beginning of the file.

w - Write mode: Opens the file for writing. If the file exists, its contents are truncated. If the file doesn’t exist, it’s created.

a - Append mode: Opens the file for appending. The file pointer is placed at the end of the file.

x - Exclusive creation mode: Opens the file for writing. If the file already exists, an error occurs. If the file doesn’t exist, it’s created.

t - Text mode: Opens the file in text mode. This is the default mode.

b - Binary mode: Opens the file in binary mode.


In [85]:
class Person:
    name="pawan"
    occupation="software developer"
    nertworth=10
    def intro(self):
        print(f"{self.name} is a {self.occupation}")
a=Person()
a.intro()
b=Person()
b.name="divyanshu"
b.occupation="data analyst"
b.intro()

harry is a software developer
divyanshu is a data analyst


In [91]:
class Person_two:
    def __init__(self,name,occ):
        self.name=name
        self.occ=occ
    def info(self):
        print(f"{self.name} is a {self.occ}")
a=Person_two("anurag","python developer")
b=Person_two("divyanshu","developer")
a.info()
b.info()

anurag is a python developer
divyanshu is a developer


*args-> taking input as tuples
**kwargs->taking input as dictionaries

DECORATERS

In [134]:
def greet(fx):
    def wrapper(*args, **kwargs):
        print("Good morning!")
        fx(*args, **kwargs)
        print("Thanks for using this function!")
       # return result
    return wrapper

@greet
def hello():
    print("Hello bhai!")

@greet
def add(a, b):
    print(a + b)

hello()
#greet(add)(1,2)
add(1,2)

Good morning!
Hello bhai!
Thanks for using this function!
Good morning!
3
Thanks for using this function!


In [144]:
class Myclass:
    def __init__(self,value):
        self._value=value
    def show(self):
        print(f"value is {self._value}")
    @property
    def ten_value(self):
        return 10*self._value
    @ten_value.setter
    def ten_value(self,new_value):
        self._value=new_value/10
        
obj=Myclass(10)
obj.ten_value=67
print(obj.ten_value)
obj.show()

67.0
value is 6.7


In [7]:
class Employee:
    def __init__(self,name,id):
        self.name=name
        self.id=id
    def showDetails(self):
        print(f"THE NAME OF EMPLOYEE {self.id} is {self.name}")
class Programmer(Employee):
    def showLanguage(self):
        print("THE DEFAULT LANGUAGE IS PYTHON")
e1=Employee("ROHAN DAS",400)
e1.showDetails()
e2=Programmer("harry",4100)
e2.showDetails()
e2.showLanguage()

THE NAME OF EMPLOYEE 400 is ROHAN DAS
THE NAME OF EMPLOYEE 4100 is harry
THE DEFAULT LANGUAGE IS PYTHON


In [9]:
class Employee:
    def __init__(self):
        self.__name="harry2"
a=Employee()
print(a._Employee__name)
print(a.__dir__())

harry2
['_Employee__name', '__module__', '__init__', '__dict__', '__weakref__', '__doc__', '__new__', '__repr__', '__hash__', '__str__', '__getattribute__', '__setattr__', '__delattr__', '__lt__', '__le__', '__eq__', '__ne__', '__gt__', '__ge__', '__reduce_ex__', '__reduce__', '__getstate__', '__subclasshook__', '__init_subclass__', '__format__', '__sizeof__', '__dir__', '__class__']


Static Method in python


In [27]:
class Main:
    def __init__(self,num):
        self.num=num
    def addtonum(self,n):
        self.num=self.num+ n
    @staticmethod
    def add(a,b):
        return a+b
result=Main.add(3,4)
print(result)
a=Main(3)
a.addtonum(6)
print(a.num)

7
9
